### ISSUE TITLE
External links do not open in new tab

### ISSUE THREAD

**Issue by zenhack** [ocdtrekkie/datasette-sandstorm#1]
the "powered by datasette" link at the bottom does nothing. Probably you want to patch it to have `target="_blank"`so it opens outside the iframe.

**Comment by ocdtrekkie** [comment]
I kinda think this might make sense to propose upstream because it is potentially destructive to click off the app inadvertently, so I've proposed it there first. We can make a package-specific patch if it's not wanted.

**Comment by ocdtrekkie** [comment]
Simon pointed out (in addition to his preference against target blank) that Datasette also displays URLs in tables, so I should probably look to implement a plugin to do this more generally in Datasette.

**Comment by zenhack** [comment]
(Fwiw, I tend to agree that *in general* `target=_blank` is not what you should do -- but in the case of sandstorm it's needed for external links to even do anything, so...)

**Comment by ocdtrekkie** [comment]
I just assembled [datasette-external-links-new-tabs](https://github.com/ocdtrekkie/datasette-external-links-new-tabs) which I believe will resolve this issue. I'll plan to include it in the next release of Datasette on Sandstorm.

**Comment by zenhack** [comment]
hm, that looks like it's actually general enough that we could even package it up as just something you can shove into apps to fix this issue in general, rather than having to patch it up on a case by case basis...

**Comment by ocdtrekkie** [comment]
Arguably, yeah, though I think it really depends on the app whether it's the most efficient solution. `<base target="_blank">` can also be a nice solution sometimes too. I personally dislike the concept of adding JS just to modify all the hyperlink tags on a page because it feels conceptually ugly/inefficient, though I'm sure compared to modern web apps it's practically zero cost.

**Comment by ocdtrekkie** [comment]
*Actually*, I think at minimum I should go ahead and add it to the Docs, because we already provide the base tag example somewhere, and this would be good too.

**Comment by ocdtrekkie** [comment]
Closing because I've pushed out Datasette 0.63 with this plugin included.
